### ISSUE TITLE
Bug: Module declaration inside .irp.f

### ISSUE THREAD

**Issue by TApplencourt** [scemama/irpf90#13]
You cannot declare a module inside a `.irp.f` it will be rip-off

foo.irp.f
```
module foo

end module foo

program toto
print*, toto
end toto
```

The generated.f90 will be sothing like that
```
module foo_mod
finalize()
end

program toto
print*, toto
end toto
```

**Comment by scemama** [comment]
Modules are not supposed to be allowed in `.irp.f` files it makes things far too complicated. You can use modules, put you have to put the in .f90 files, outside the scope of IRP.
