### ISSUE TITLE
implicit none warning

### ISSUE THREAD

**Issue by maxlevesque** [scemama/irpf90#6]
Why not adding `-fimplicit-none` as the default in the makefile ?
I am testing IRPF90 v 1.5.0.

I have had a hard time debugging an implicit declaration I though was ok because of the implicit reference paradigm...

**Comment by scemama** [comment]
I don't like to have such important behavior in the compile flags. I think it's better to put it hard coded inside the providers/functions/subroutines such that it it much more difficult to remove.
A warning mentioning you forgot ``implicit none`` could be nice.
