### ISSUE TITLE
intrinsic ALL() in IRPF90's ASSERT()

### ISSUE THREAD

**Issue by maxlevesque** [scemama/irpf90#7]
It would be quite nice to be able to do the following
```fortran
ASSERT( all( array >= 0 ) )
```
where `array` is a multidimensional array.
https://gcc.gnu.org/onlinedocs/gfortran/ALL.html

Of course, `any()` is also useful.

**Comment by scemama** [comment]
Solved in version 1.6.9.
Thanks for posting this issue
