### ISSUE TITLE
touch behavior

### ISSUE THREAD

**Issue by maxlevesque** [scemama/irpf90#8]
The following sample code does not compile. Strange if I refer to [irpf90's gitbook](https://scemama.gitbooks.io/irpf90/content/IRPF90/Touch.html).

```fortran
program foo
    implicit none
    print*, mmax
    touch mmax
    print*, mmax
end program
```

As far as I understand, it should call 3 times the provider mmax.

```fortran
begin_provider [ integer, mmax ]
    implicit none
    mmax = 1
end_provider
```

but `make` returns

```bash
irpf90  
gfortran -I IRPF90_temp/  -O2 -ffree-line-length-none -I . -c IRPF90_temp/main.irp.F90 -o IRPF90_temp/main.irp.o
gfortran -I IRPF90_temp/  -o main IRPF90_temp/main.irp.o IRPF90_temp/main.irp.module.o IRPF90_temp/irpf90.a 
IRPF90_temp/main.irp.o: In function `foo_':
main.irp.F90:(.text+0x70): undefined reference to `touch_mmax_'
collect2: error: ld returned 1 exit status
irpf90.make:11: recipe for target 'main' failed
make: *** [main] Error 1
```

I believe this comes from irpf90's `touch` being called from the main. Expected behavior?

**Comment by scemama** [comment]
You can't define a provider in the same file than a main program as this provider will always be missing for any other program.

**Comment by maxlevesque** [comment]
OK, thanks a lot for your very fast answer.
Note that the same program without line `touch mmax` behaves as expected, even if provider is in the same file as main.

Then I propose to add some report to the user in this case.
A first pass of the parser checking that no provider is defined "*in the same file than a main program as this provider will always be missing for any other program"*.

**Comment by scemama** [comment]
Also, if you ``TOUCH x``, ``x`` will never be recomputed. It is supposed to be valid before you ``TOUCH`` it. Only what depends on ``x`` will be recomputed. Similarly, if you do : 

``` bash
$ make
$ touch toto.o
$ make
```

you will not recompile ``toto.o``, but you will redo only the linking stage (whih depends on ``toto.o``).

**Comment by maxlevesque** [comment]
I get it, thanks.
